### ISSUE TITLE
Convert to PCRaster format doesn't work with LDD data type

### ISSUE THREAD

**Issue by openSourcerer9000** [pcraster/pcraster#345]
Convert to PCRaster format doesn't work with LDD data type, spits out a raster of all 1's. LDD datatype is required for any delineation operations, catch 22. Also, why does LDD take an hour to compute instead of 2 minutes? I thought this was a new lib.

Looking forward to seeing where this lib goes, but if you're gonna require a custom GIS format it better be worth the nonstandardness.

**Comment by kordejong** [comment]
Thank you for reporting this issue. To better understand what you are trying to do, can be please share the commands that you use and a description of the source data (size, raster format, data type)? A minimal example with which we can reproduce the issue would be ideal.

**Comment by jantin1** [comment]
Hello I can confirm this problem exists in the QGIS plugin (QGIS version 3.28.2) on Windows 10. I have installed PCRaster backend with OSGeo4W and the plugin to access the functions from the processing menu. When converting a file to the .map format I get a flat map of 1s when the LDD datatype is chosen. A file is created correctly when I order a scalar datatype. I tried what the original issue suggested: convert a map  to a scalar .map and then convert the scalar .map to LDD .map. The effect is still a raster of all 1s. 
I work in the QGIS GUI. I use a 2000 x 4000 pixel DEM, with 1 meter spatial resolution, which weighs around 8 MB.

**Comment by kordejong** [comment]
Can you explain to me what you want to achieve and which values are in the input raster?

An LDD raster is a raster containing codes that represent drain directions. An LDD raster is normally created by the `lddcreate` operation, that takes a DEM as input. When casting from another raster, it is important that the range of source values is within the range of correct drain direction codes ([1, 9]).
In general I would advise against casting to an LDD raster. It is very easy for the result to be an unsound drainage network. If you must, the `lddrepair` operation may be useful.

- https://pcraster.geo.uu.nl/pcraster/4.4.0/documentation/pcraster_manual/sphinx/secdatbase.html#ldd-data-type
- https://pcraster.geo.uu.nl/pcraster/4.4.0/documentation/pcraster_manual/sphinx/op_lddcreate.html
- https://pcraster.geo.uu.nl/pcraster/4.4.0/documentation/pcraster_manual/sphinx/op_ldd.html
- https://pcraster.geo.uu.nl/pcraster/4.4.0/documentation/pcraster_manual/sphinx/op_lddrepair.html

**Comment by jantin1** [comment]
I want to create a Strahler order map. I have a DEM in .tiff format. I have created a LDD map with the` lddcreate`  operation (the one which takes around 2 hours to complete) then haphazardly saved it as a geotiff. I have loaded the geotiff to QGIS and upon discovering, that the `streamorder` tool requires the .map format I tried to convert the product with the conversion function. Effect of the last operation is a uniform map of "1". When I try to feed this bad file to `streamorder` I get an error saying it's a boolean datatype:
`Traceback (most recent call last):
File "C:\Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pcraster_tools\processing\algorithms\pcraster_streamorder_algorithm.py", line 87, in processAlgorithm
strahler = streamorder(LDD)
File "C:\OSGeo4W\apps\Python39\lib\site-packages\pcraster\operations.py", line 3540, in streamorder
raise RuntimeError("streamorder: %s" % (str(exception)))
RuntimeError: streamorder: argument nr. 1 of function 'streamorder': type is boolean, legal type is ldd
`
I will try to re-create my LDD map and save it as a .map and see if it makes a difference.

**Comment by kordejong** [comment]
I see. Yes, when using PCRaster operations it is best to keep the raster formatted in the PCRaster format. PCRaster uses the notion of value types (boolean, ldd, nominal, ordinal, scalar, and directional), to prevent users from accidentally calculating the square root of a soil map, for example. This additional piece of information is stored in the PCRaster raster format.

Apart from that, it seems that the conversion from the PCRaster LDD raster to Geotiff and back resulted in a PCRaster boolean raster. That should not happen. In case the Geotiff contains the correct LDD codes, then converting it to a PCRaster LDD raster should work fine. But instead of fixing this step, keeping the data in PCRaster raster format should solve the issue also.

`lddcreate` is one of the slowest operations in PCRaster. In another project we are working on alternative implementations of the PCRaster operations that make better use of parallel hardware (https://lue.computationalgeography.org). This new package is not ready for production yet, though.

**Comment by esnyder-rve** [comment]
This is still an issue. I created a flow direction raster in SAGA (because PCRaster didn't complete the lddcreate within >24hrs), and re-mapped the classification into PCRaster's schema. I am unable to convert the final tiff file into PCRaster's map format.
